/************************
* LEGACY MAP of         *
* Home of Cold Blood    *
* done by               *
* Rainer Gottwald       *
* r.gottwald@freenet.de *
************************/

var home_of_cold_blood = new Array();

home_of_cold_blood['level'] = 'Level 4';
home_of_cold_blood['title'] = 'Home of Cold Blood';
home_of_cold_blood['map'] = [
  '???################################?########????',
  '???#           W    W             #?#      ##???',
  '???# #w# #w# #w#    # ###S###S### #?#       h???',
  '???# # # # # # #    # # #D#?#D#?# #?#      ##???',
  '???# # # # # # #    # # # #?# #?# #?# #########?',
  '#### #D# #D# #D# # ## # # #?# #?# #?# #?#     d?',
  '# T#W# #e# #e# #a#### # #D#?#D#?# #?# #?# ######',
  '# ##            ##### #W# ### ### #?#D#?#Df  W #',
  '#                SE   l         # ###S###S#### #',
  '####            ##### f         W  E  SE  SE   #',
  '???#W# #g# #g# ##???# #         # ###S###S#### #',
  '???# #D# #D# #D#????# #W# ### ### # #D#?#Df  W #',
  '???# # # # # # #????# # #D#?#D#?# # # #?# ######',
  '???# # # # # # #????# # # #?# #?# # # #?#     d?',
  '???# #u# #u# #u#????# # # #?# #?# # # ##########',
  '???#           #????# # #D#?#D#?# # #          #',
  '???######      #????# ###S###S### # #       ## #',
  '????????# ######????#             # #       ## #',
  '????????# #   #####################W########## #',
  '????????#D#   W      #        #    W    W    # #',
  '????????# ##### #### ####### ## ####   S###### #',
  '????????#     # #  # #            h#  SS       #',
  '????????####  # #  # ####### ## ####   S########',
  '???????????#  # #  # #Z      ##    W    W    #??',
  '???????????#  # #  # ####### ######W##########??',
  '???????????#  W W  # #       #????#     #???????',
  '???????????#  WSW  # ####### #????#######???????',
  '???????????#  WWW  # #       #??????????????????',
  '???????????#  #N#  # ####### #??????????????????',
  '???????????##u###u##         #??????????????????',
  '???????????????????###########??????????????????'
  ];
  
home_of_cold_blood['infos'] = [
  ' 2| 5|Wight Master,Fire King',
  ' 2| 9|Night Eye',
  ' 2|13|Fire King',
  ' 2|15|Wight Master,Night Eye',
  ' 2|17|Secret Switch|Opens wall to the west',
  ' 2|20|Fire King',
  ' 2|22|Secret Switch|Opens wall to the west',
  ' 2|28|Wight Master',
  ' 2|34|Vase|Remove paralysis potion x2',
  ' 2|38|Vase|160 gp, Leather Skirt AC:2, Full mana potion, Remove paralysis potion',
  ' 2|39|Wight',
  ' 3|45|Shelf|Quiver 30 poison arrows',
  ' 4|18|Invoker, Medusa Queen',
  ' 4|39|Wight Master',
  ' 5| 7|Adept, Invoker',
  ' 5|11|Evil Eye,Invoker',
  ' 5|15|Evil Eye,Medusa Queen',
  ' 5|38|Wight',
  ' 6| 5|Secret Switch|Removes the wall to the south',
  ' 6|26|Evil Eye,Adept',
  ' 6|30|Adept,Invoker',
  ' 6|47|Well|"After drinking from the well, you feel you\'re blessed."',
  ' 7| 2|Vase|100 gp, Full healing potion x2, Scroll of Cure poison',
  ' 7| 3|Entrance|Entrance from Sohl\'s Cave',
  ' 7| 9|Shelf|Priest Necklace AC:0 +5 endurance',
  ' 7|13|Shelf|Opal Ring AC:0 +5 strength',
  ' 7|17|Well|"After drinking from the well, you feel that the gods are with you for an hour"',
  ' 7|24|Wight,Invoker,Medusa Queen',
  ' 8|43|Shelf|250 gp',
  ' 8|47|Secret Switch|Removes the wall to the west',
  ' 9| 2|Vase|Remove paralysis potion x2, Scroll of Firewall',
  ' 9| 7|Contact|Opens the doors to the north and south',
  ' 9|11|Contact|Opens the doors to the north and south',
  ' 9|15|Contact|Opens the doors to the north and south',
  ' 9|18|Pressure Plate|Opens the door if all 6 switches in the chamber before were switched',
  ' 9|23|Sign|"Thinking of finishing the test? You fool: the battle has just begun!"',
  '10|23|Shelf|Pass key',
  '10|24|Contact|Opens secret doors to the north and south',
  '10|28|Master Lich',
  '10|36|Door|You need the Pass key to get through',
  '10|42|Invoker,Wight Master',
  '10|45|Wight Master,Night Eye,Evil Eye,Invoker, Adept',
  '11| 9|Shelf|250 gp',
  '11|13|Shelf|250 gp',
  '11|32|Medusa Queen',
  '12| 5|Secret Switch|Opens wall to the north',
  '12|43|Shelf|250 gp',
  '12|47|Secret Switch|Removes the wall to the west',
  '13| 7|Invoker,Fire King',
  '13|11|Night Eye,Adept',
  '13|15|Evil Eye,Night Eye',
  '13|24|Wight Master,Night Eye,Wight Master',
  '14|26|Invoker,Fire King',
  '14|30|Invoker,Medusa Queen',
  '14|47|Well|"After drinking from the well, you feel you\'re full ow power"',
  '15|38|Wight',
  '16| 9|Medusa Queen,Invoker,Medusa Queen,Night Eye',
  '16|15|Vase|200 gp, Amulet AC:0, Full healing potion',
  '16|39|Wight Master',
  '17|14|Evil Eye',
  '17|15|Vase|120 gp, Leather Shirt AC:2, Full mana potion, Full healing potion',
  '17|40|Wight',
  '17|42|Night Eye',
  '18|22|Vase|Rusty Chain Shirt AC:1, Remove paralysis potion',
  '18|28|Wight Master',
  '18|34|Vase|Remove paralysis potion x2, Scroll of Poison cloud',
  '18|36|Fire Lord,Master Lich',
  '18|41|Wight Master',
  '19|10|Invoker',
  '20|29|Master Lich,Medusa Queen,Invoker',
  '20|30|Vase|300 gp, Rusty Chain Shirt AC:1, Remove paralysis potion x2',
  '20|35|Fire King,Fire Lord',
  '20|42|Night Eye,Wight Master,Fire King',
  '20|45|Vase|300 gp, Gold Ring AC:0, Remove paralysis potion',
  '22|14|Vase|Quiver 5 iron arrows, Full mana potion',
  '22|18|Vase|Female Battle Skirt AC:3, Full healing potion, Scroll of Mass heal',
  '22|19|Vase|Full mana potion, Scroll of Mass heal, Scroll of Harm undead',
  '22|35|Shelf|250 gp',
  '22|41|Night Eye,Wight Master',
  '24|23|Mana Sphere',
  '24|29|Night Eye,Invoker,Invoker,Medusa Queen',
  '24|35|Medusa Master',
  '24|42|Night Eye,Wight Master,Fire King',
  '26|14|Wight Master,Invoker,Medusa Queen,Night Eye,Fire King,Master Lich',
  '26|18|Night Eye,Wight Master,Fire King,Master Lich,Medusa Queen,Invoker',
  '26|36|Medusa Queen,Medusa Master',
  '27|16|Pressure Plate|Closes the wall in front of you and opens the secret walls',
  '28|28|Master Lich',
  '29|16|Statue|Sphere of Guards',
  '30|14|Switch|Needed to get access to the Sphere',
  '30|18|Switch|Needed to get access to the Sphere',
  '30|21|Wight Master,Wight Master',
  '32|50|Engine made by Markus Birth, map by Rainer Gottwald|&lt;<A HREF="mailto:mbirth@webwriters.de">mbirth@webwriters.de</A>&gt; &amp; &lt;<A HREF="r.gottwald@freenet.de">r.gottwald@freenet.de</A>&gt;'
  ];

AddMenu('home_of_cold_blood');
